### ISSUE TITLE
Compile for non popcnt hardware?

### ISSUE THREAD

**Issue by rwbc** [altarchess/Altar#1]
Would you mind offering a compile for older non popcnt 64-bit hardware?
My attempt in compiling it in msys2 was not successful due to several errors
and guessing the compiler options.

Guenther

**Comment by altarchess** [comment]
Altarchess uses pext/pdep as well as popcnt. I feel changing attackset generation would be too much work considering Altarchess is no longer beeing developed. Some concepts from Altarchess have been/are beeing implemented in Koivisto tho. Might wana look at https://github.com/Luecx/Koivisto :)

**Comment by rwbc** [comment]
I understand this. Good luck with Koivisto, which I had already compiled a few times before my post above ;-)
